import {ICommand} from './types'

export const commands: ICommand[] = [
  {
    id: '1',
    name: 'M414',
    description: 'Выбор языка интерфейса',
    details: {
      text: 'Переопределенная стандартная команда выбора языка интерфейса',
    },
    params: [
      {
        name: 'S',
        description: 'Выбор языка интерфейса',
        hint: 'Выберете язык',
        label: 'Язык интерфейса',
        value: 0,
        selectableValues: [
          {label: 'English', value: 0},
          {label: 'Русский', value: 1},
          {label: 'Український', value: 2},
          {label: 'Nederlands', value: 3},
        ],
        isActive: true,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: '2',
    name: 'M81',
    description: 'Отключить питание',
    details: {
      text: 'Отключите высоковольтный источник питания. Если плата не питается от другого источника, это также может привести к отключению электроники.',
      url: 'https://marlinfw.org/docs/gcode/M081.html',
    },
    params: [
      {
        name: 'C',
        label: 'Взять параметры',
        description: '',
        hint: 'Взять параметры из настроек модуля управления питанием',
        value: false,
      },
      {
        name: 'D',
        label: 'Задержка выключения',
        description: '',
        hint: '(delay) задержка выключения [0..255] секунд',
        value: 0,
        min: 0,
        max: 255,
      },
      {
        name: 'T',
        label: 'Ожидание охлаждения хотэнда',
        description: '',
        hint: '(temperature) - ожидание охлаждения хотэнда',
        value: 0,
      },
      {
        name: 'F',
        label: 'Вентилятор включен',
        description: '',
        hint: '(fan) - включение вентилятора при ожидании охлаждения',
        value: false,
      },
    ],
  },
  {
    id: '3',
    name: 'M851',
    description: 'Смещение датчика XYZ',
    details: {
      text: 'Установите расстояние XYZ от сопла до точки срабатывания датчика. Эти смещения необходимы для того, чтобы прошивка знала, как измерять слой и где находятся измеряемые точки по отношению к соплу, и наоборот.',
      url: 'https://marlinfw.org/docs/gcode/M851.html',
    },
    params: [
      {name: 'X', label: 'X', description: '', hint: '', value: 0},
      {name: 'Y', label: 'Y', description: '', hint: '', value: 0},
      {name: 'Z', label: 'Z', description: '', hint: '', value: 0},
      {name: 'C', label: 'Clearance (shui)', description: '', hint: '', value: 0},
      {name: 'L', label: 'Z probe low point (shui)', description: '', hint: '', value: 0},
      {name: 'N', label: 'Number of failed probes (shui)', description: '', hint: '', value: 0},
      {name: 'B', label: 'Bltouch (0/1) (shui)', description: '', hint: '', value: 0},
      {name: 'I', label: 'Inaccuracy (shui)', description: '', hint: '', value: 0},
    ],
  },
  {
    id: '',
    name: '',
    description: '?',
    details: {
      text: '?',
    },
    params: [],
    isNotDuplicate: true,
  },
  {
    id: 'M414',
    name: 'M414',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'G21',
    name: 'G21',
    description: '?',
    details: {
      text: '?',
    },
    params: [],
    isNotDuplicate: true,
  },
  {
    id: 'M2000.0',
    name: 'M2000.0',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2000.1',
    name: 'M2000.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M92',
    name: 'M92',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M201',
    name: 'M201',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M203',
    name: 'M203',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M204',
    name: 'M204',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M205',
    name: 'M205',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'J',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M206',
    name: 'M206',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M207',
    name: 'M207',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M208',
    name: 'M208',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M209',
    name: 'M209',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M281',
    name: 'M281',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M851',
    name: 'M851',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M145',
    name: 'M145',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M301',
    name: 'M301',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M304',
    name: 'M304',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M603',
    name: 'M603',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M302',
    name: 'M302',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M852',
    name: 'M852',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'J',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'K',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M425',
    name: 'M425',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2013',
    name: 'M2013',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'V',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2013.1',
    name: 'M2013.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2013.2',
    name: 'M2013.2',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2013.3',
    name: 'M2013.3',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2008',
    name: 'M2008',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2001',
    name: 'M2001',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'K',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2002',
    name: 'M2002',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2002.1',
    name: 'M2002.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'X',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2002.2',
    name: 'M2002.2',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2003',
    name: 'M2003',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Q',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M420',
    name: 'M420',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2004',
    name: 'M2004',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2004.1',
    name: 'M2004.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2009.1',
    name: 'M2009.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2009.2',
    name: 'M2009.2',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2009',
    name: 'M2009',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2009.3',
    name: 'M2009.3',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2009.4',
    name: 'M2009.4',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'K',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'K',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2009.5',
    name: 'M2009.5',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2016',
    name: 'M2016',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'O',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'O',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'Y',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'O',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'U',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'I',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2016.1',
    name: 'M2016.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'O',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2030',
    name: 'M2030',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2020',
    name: 'M2020',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'K',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2020.1',
    name: 'M2020.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2023',
    name: 'M2023',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'Z',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'K',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2014',
    name: 'M2014',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2017',
    name: 'M2017',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'K',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'B',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2034',
    name: 'M2034',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'W',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'L',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2025',
    name: 'M2025',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'F',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'A',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2019.1',
    name: 'M2019.1',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'M',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'C',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2019.2',
    name: 'M2019.2',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'N',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'H',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'D',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'P',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M2019',
    name: 'M2019',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'T',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M500S',
    name: 'M500S',
    description: '?',
    details: {
      text: '?',
    },
    params: [],
    isNotDuplicate: true,
  },
  {
    id: 'M2005',
    name: 'M2005',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'E',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
  {
    id: 'M0',
    name: 'M0',
    description: '?',
    details: {
      text: '?',
    },
    params: [
      {
        name: 'S',
        label: '?',
        description: '',
        hint: '?',
        value: 0,
      },
      {
        name: 'R',
        label: '?',
        description: '',
        hint: '?',
        value: false,
      },
    ],
    isNotDuplicate: true,
  },
]
